version: "3"
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:trustme@172.17.0.1:5432/omlpi_dev
    ports:
      - "3000:1225"
    command: npm start
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
